### ISSUE TITLE
About rendered lists

### ISSUE THREAD

**Issue by IsaaLeonardo** [TriDiamond/Obsidian-Obsidianite#27] opened 2021-03-17 17:57 UTC
I love this theme and I've chosen to use it in a daily basis! I want to show one thing I don't like in order to make it better.

I usually make lists with a line between every element, and not one element below another. In _edit mode_ it would show just like this:

![Sin título](https://user-images.githubusercontent.com/69018559/111514318-ff33ef00-8727-11eb-834c-3a5c131812db.png)

And the problem I find is, in _preview mode_, the list shows like this:

![Sin título](https://user-images.githubusercontent.com/69018559/111514660-53d76a00-8728-11eb-86ac-ec90724d274f.png)

I just want to find a way to make the list shows ok on the _preview mode_.

Thank you for your attention. :D

**Comment by Yozh2** [comment] 2021-04-06 08:48
Duplicate of #25 

Found a crutch-like solution in #25 → do not insert empty lines between list items.

**Closed** 2021-04-06 09:00 UTC

**Comment by IsaaLeonardo** [comment] 2021-04-07 20:59
> Duplicate of #25
> 
> Found a crutch-like solution in #25 → do not insert empty lines between list items.

Perfect! Thank you very much!
